<div data-bind="scope:'suraj-component'">
	<!--ko template:getTemplate()-->
    <!--/ko-->
</div>

<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components":{
					"suraj-component":{
						"component":"Suraj_UiComponent/js/component",
                        "config":{
                            "template":"Suraj_UiComponent/demo"
                        }
   					}
				}
			}
		}
	}
</script>
